### PR TITLE
Implemented Search functionality

### PR DESCRIPTION
**Pull request by JosephNahas**

### CODE REVIEW

**Comment by JosephNahas** [comment]
Search functionality implemented, please test and let me know of any issues

**Comment by aM3dia** [comment]
Looks good! Now to see if we can figure out how to get the results to show when the screen size is 850px 🙈

**Comment by Jneyugn** [comment]
Yay, it works!

**Comment by Attialaa77** [comment]
I had the pleasure of testing the web version, and I must say, I am thoroughly impressed! Here’s what I loved about it:
User Interface: The design is clean and visually appealing. The layout is intuitive, and navigation is seamless.
Everything is easy to find, and the responsive design works great.
Bug-Free Experience: I didn’t encounter any noticeable bugs or glitches, which speaks volumes about the quality of the code and testing involved.

**Comment by Attialaa77** [comment]
if you let me touch every file or just edit it and paste it in the group chat I will make the code always looks elegant and clean and it is very easy to read. it won't change much it will only make it more clean.
i will adds tabs to the various lines to make it more pleasant for people to read. and i will add a few export tools to then grab this better-looking code.
why do I want to do this?
Actually the computer doesn’t care how your code looks. As long as the code is written accurately, the computer is going to ignore tabs, spaces, and other white spaces (unless, of course, you’re writing in a code that uses that space, such as Python).
However, a human reading your code is going to appreciate indents to help separate out the lines and make it easier to read.

**Pull request merged**
