### PR TITLE
Resize games and made the navigation a scroll for smaller screens

### PR DESCRIPTION
**Pull request by aM3dia**

### CODE REVIEW

**Comment by JosephNahas** [comment]
The search results do not show up on screens with a width 800 and smaller

**Comment by aM3dia** [comment]
> The search results do not show up on screens with a width 800 and smaller

Is this something I can fix through CSS or was this something implemented through JS?

**Comment by JosephNahas** [comment]
actually i see them now, if you zoom in and scroll down you can see them, they are just stuck under the header

**Comment by JosephNahas** [comment]
the same thing is happening with the categories sub nav

**Comment by aM3dia** [comment]
> the same thing is happening with the categories sub nav

Oh! Wasn't aware of that! I totally forgot to check the categories subnav. I'm thinking it may have to do with the z-index then since the header height increases.

**Comment by Jneyugn** [comment]
yayy

**Comment by Jneyugn** [comment]
yayy

**Comment by Jneyugn** [comment]
will check soon!

**Pull request merged**
